### ISSUE TITLE
Add configuration to enable pretty-print of json

### ISSUE THREAD

**Issue by matosf** [zalando/twintip-spring-web#4]
Add support for a new property:

```
twintip:
   ...
   pretty-print: true
```

Code change will be something like this:

```
    @Autowired
    public SchemaResource(
            @Value("${twintip.yaml}") final Resource yamlResource,
            @Value("${twintip.pretty-print:false}") final Boolean prettyPrint) throws IOException {
        this.objectMapper = new ObjectMapper();
        if (prettyPrint) {
            objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
        }
        apiYamlValue = consume(yamlResource.getInputStream());
        apiJsonValue = yamlToJson(apiYamlValue);
    }
```

The use case of this is that the client developer can look at the JSON in the browser without any extension like JSONView to make it readable.

**Comment by whiskeysierra** [comment]
I'd just enable it by default without a way to change it. Would that cause any issues?

**Comment by matosf** [comment]
That's also fine.
Em 23/04/2016 10:24 da tarde, "Willi Schönborn" <notifications@github.com>
escreveu:
